//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkymedTime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkymedTime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ATLETA&quot;:[{&quot;atleta_id&quot;:1,&quot;nome_popular&quot;:&quot;DANIEL&quot;,&quot;nome&quot;:&quot;Daniel de Sousa Brito&quot;,&quot;posicao&quot;:&quot;Goleiro&quot;,&quot;sigla&quot;:&quot;GOL&quot;,&quot;Camisa&quot;:1},{&quot;atleta_id&quot;:2,&quot;nome_popular&quot;:&quot;Anthoni&quot;,&quot;nome&quot;:&quot;Anthoni Spier Souza&quot;,&quot;posicao&quot;:&quot;Goleiro&quot;,&quot;sigla&quot;:&quot;GOL&quot;,&quot;Camisa&quot;:24},{&quot;atleta_id&quot;:3,&quot;nome_popular&quot;:&quot;BRUNO MÉNDEZ&quot;,&quot;nome&quot;:&quot;Bruno Méndez Cittadini&quot;,&quot;posicao&quot;:&quot;Zagueiro&quot;,&quot;sigla&quot;:&quot;ZAG&quot;,&quot;Camisa&quot;:22},{&quot;atleta_id&quot;:4,&quot;nome_popular&quot;:&quot;ZÉ GABRIEL&quot;,&quot;nome&quot;:&quot;José Gabriel dos Santos Silva&quot;,&quot;posicao&quot;:&quot;Zagueiro&quot;,&quot;sigla&quot;:&quot;ZAG&quot;,&quot;Camisa&quot;:35},{&quot;atleta_id&quot;:5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeJson {
            get {
                return ResourceManager.GetString("TimeJson", resourceCulture);
            }
        }
    }
}
